# Git Introduction {}

## What is Git?
Git is a distributed version control system that was developed by Linus Torvalds for working on the Linux kernel. Despite its original use case, it is used for many software projects. It has become a popular choice for version control systems and becomes a powerful tool once the basics are learned.

Users traditionally interface with Git through a Unix shell, or commandline environment, but there are several graphical or GUI options for interfacing with the tool. More information about this can be found in the Appendix section of this documentation.

Git, and version control systems more generally, enable users to store different versions of files and keep track of changes between those versions. Git helps users document a history of changes, including mistakes, to their projects and enables them to switch to any past version. The result is essentially a list of different versions of a project that represent its state during a given time.

## What is a Repository?
A Git repository is a directory, or folder, where version tracking and history has been initialized. One can check if version tracking is initialized in a directory by looking for a hidden ".git" subdirectory (you may have to enable a, "show hidden files" feature in your file manager if you wish to do this). This hidden directory stores metadata about a project, metadata of the files in that project, and the detailed history of that project. Note that the actual project files reside in the directory that contains the hidden ".git" directory, not the ".git" directory itself.

A repository is an entity that is local in nature, meaning it resides on your machine and you treat it the same way you would any other file. As a result, any changes you make are yours and you must deliberately choose to share those changes if you want others to see them.

## What Is A Commit?
A commit is a change to a repository and you do this when you implement a change to your project. This change can be as simple as the addition of a new file to your project or as complex as a series of changes across multiple files. A user "commits" to a repository when they want to store a new version of a project. When this is done, they now have a distinct version of the project that they can go back to and view the changes from one version to another.

Generally, commits should contain a change that is singular in purpose. If two separate parts of a project were to be changed, they should be "committed" to the repository separately. A commit represents a point in time, a specific version of your project, and if two changes representing separate parts of a project were to end up in the same commit, then it would make the history of your project confusing or not clear. It is desirable to be able to understand the evolution of a project as changes are made and this becomes more difficult if changes are not distinct.

A commit will have a message associated with it. This message should describe why changes were made and what purpose these changes fulfill. Each commit will have a log of what aspects of your project have changed and a commit message should also briefly describe what changes were made if they are not self-explanatory.

For the sake of argument, let's say you change a readme file to include a link to a funding page for your project. The following is an example of a poor commit message.


> Changed the readme.

A better message would be:


> Added a link to the funding page.

An even better message would be:


> Added a link to the funding page in the reference section of the readme. Those who want to fund the project no longer have to email asking how to support it.

## Understanding Distributed
As was stated previously, Git is a distributed version control system which means that every repository, including ones on your local machine, do not require some centralized service to function.

When you share changes with others, you are simply merging histories or syncing changes rather than performing some sort of special transaction with a centralized service. It is important to have a conceptual understanding of this because this is how you use Git when working on a project. You make and commit changes locally, then you can share those changes with the rest of the world. You cannot share changes with the rest of the world if you have not committed those changes locally.

## Push
The act of "push", or "pushing", is when changes are uploaded to remote locations. Once a change is made and committed to your local repository, you can then send a copy of your changes to a remote location (push). This remote location is simply housing another copy of that repository. Anyone with the proper permissions can push to a remote repository so that someone else can download (pull) their changes.

## Pull
The act of "pull", or "pulling", is when changes are downloaded from remote locations. If someone pushes a change into a remote repository, you can download (pull) that change and sync it with your local repository. Anyone can pull changes from a remote repository and sync it with their local version. This is also how repositories are initially downloaded if they are not present on your machine.


## The Log
Each Git repository has its own history that details which files have changed, who changed them, and their stated reasons for changing them. This can be viewed by using the log functionality of Git. The log will give you an overview of each project change by showing all the aforementioned information as well as detailing the exact changes. This can be used to track project changes and understand its history.
